/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

public class App {

    public static void main(String[] args){

        System.out.println("\n");

        //item 1.3(a) - Readme.md - criar duas instâncias de Lampada
        Lampada led = new Lampada();
        Lampada alogenica = new Lampada();

        //itens 1.3(b)e(c) - Readme.md - ligar uma instância e desligar a outra e imprimir o estado
        led.ligar();
        System.out.println("Lampada de led está : " + ((led.verEstado())? "Ligada":"Desligada"));
        alogenica.desligar();
        System.out.println("Lampada Alogênica está: " + ((alogenica.verEstado())? "Ligada":"Desligada"));
        System.out.println("\n\n");


        Pessoa pessoa0 = new Pessoa("Alice", 22);
        Pessoa pessoa1 = new Pessoa("Bruno", 25);
        pessoa1.setIdade(26);
        pessoa1.setIdade(27);
        pessoa1.setIdade(28);

    }
}
