/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

public class App {

    public static void main(String[] args){

        System.out.println("\n");

        //item 1.3(a) - Readme.md - criar duas instâncias de Lampada
        Lampada led = new Lampada();
        Lampada alogenica = new Lampada();

        //itens 1.3(b)e(c) - Readme.md - ligar uma instância e desligar a outra e imprimir o estado
        led.ligar();
        System.out.println("Lampada de led está : " + ((led.verEstado())? "Ligada":"Desligada"));
        alogenica.desligar();
        System.out.println("Lampada Alogênica está: " + ((alogenica.verEstado())? "Ligada":"Desligada"));
        System.out.println();

        //Item 2.3(a) - Readme.md. Criar duas pessoas, nessas condições
        Pessoa alice = new Pessoa("Alice", 22);
        Pessoa bruno = new Pessoa("Bruno", 25);
        System.out.println();

        //Item 2.3(b) - Readme.md. Comemorar 3x felicidades ao Bruno
        bruno.felizAniversario();
        bruno.felizAniversario();
        bruno.felizAniversario();
        System.out.println();

        //Item 2.3(c) - Readme.md. Imprimir a idade das duas pessoas
        System.out.println(alice.getNome() + " tem " + alice.getIdade() + " anos.");
        System.out.println(bruno.getNome() + " tem " + bruno.getIdade() + " anos.\n");

        //Item 2.3(d) - Readme.md. Teste de regra para idade < 0
        alice.setIdade(-44);
        System.out.println();

        //Item 2.3(e) - Readme.md Teste set de nome vazio
        bruno.setNome("");
        System.out.println(bruno.getNome());

        //Item 3.3(a) - Readme.me - criar um retângulo com 5 largura e 4 altura
        Retangulo quadrilatero = new Retangulo(5,4);

        System.out.println("\nPara um retângulo de " + quadrilatero.getLargura() + " larg. com " + quadrilatero.getAltura()
                +" de altura a área deste retângulo é "+ quadrilatero.getArea() + " e o perímetro é " + quadrilatero.getPerimetro() + "\n");

    }
}
